### ISSUE TITLE
Failed to activate the erb-helper package

### ISSUE THREAD

**Issue by matheuscandido** [migeorge/erb-helper#3]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.192.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.3
**Thrown From**: [erb-helper](https://github.com/migeorge/erb-helper) package, v0.2.1
### Stack Trace

Failed to activate the erb-helper package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.module.exports.activate (/Users/matheuscandido/.atom/packages/erb-helper/lib/erb-helper.coffee:4:25)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:222:19)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:203:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:147:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:195:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:434:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:418:29
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app/src/config.js:298:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:413:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:394:46)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
codeigniter, v0.1.3
emmet, v2.3.7
erb-helper, v0.2.1
rails-snippets, v1.9.0
set-syntax, v0.2.1
seti-syntax, v0.3.3
seti-ui, v0.6.3

# Dev
No dev packages
```

**Comment by migeorge** [comment]
Hi @matheuscandido,
erb-helper now conforms with the new Atom 1.0 API which means your issue should be solved and you should be able to use erb-helper in 1.0 preview mode.

Thanks for the bug report!
